name: CI & Dependency Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest       # ← runs-on belongs to build-test, not under steps
    steps:
      - name: Checkout code       # ← each item under steps must start with `-`
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'    # ← quoted so YAML doesn’t parse it as a float

      - name: Install & Test
        run: |
          npm ci
          npm test
